#!/bin/bash   

folder=$1

cd RISULTATI
mkdir $folder
cd $folder
cp $CMSSW_BASE/src/Analyzer/EDBRTauAnalyzer/runOnQueue.sh .

### analyzer - PERUGIA ###
./runOnQueue.sh ZH1000 25 cms-short analyzer ZH1000 PERUGIA MC $folder
./runOnQueue.sh ZH1500 25 cms-short analyzer ZH1500 PERUGIA MC $folder
./runOnQueue.sh ZH2000 25 cms-short analyzer ZH2000 PERUGIA MC $folder
./runOnQueue.sh ZH2500 25 cms-short analyzer ZH2500 PERUGIA MC $folder
./runOnQueue.sh RunA 200 cms-medium analyzer RunA PERUGIA data $folder
./runOnQueue.sh RunB 200 cms-medium analyzer RunB PERUGIA data $folder
./runOnQueue.sh RunC 200 cms-medium analyzer RunC PERUGIA data $folder
./runOnQueue.sh RunD 200 cms-medium analyzer RunD PERUGIA data $folder
./runOnQueue.sh DY100 250 cms-medium analyzer DY100 PERUGIA MC $folder
./runOnQueue.sh DY70 250 cms-medium analyzer DY70 PERUGIA MC $folder
./runOnQueue.sh DYM50_100 250 cms-medium analyzer DYM50_100 PERUGIA MC $folder
./runOnQueue.sh DYM50_70 250 cms-medium analyzer DYM50_70 PERUGIA MC $folder
./runOnQueue.sh WW 250 cms-medium analyzer WW PERUGIA MC $folder
./runOnQueue.sh WZ 250 cms-medium analyzer WZ PERUGIA MC $folder
./runOnQueue.sh ZZ 250 cms-medium analyzer ZZ PERUGIA MC $folder
./runOnQueue.sh TT 250 cms-medium analyzer TT PERUGIA MC $folder
./runOnQueue.sh QCD250 250 cms-medium analyzer QCD250 PERUGIA MC $folder
./runOnQueue.sh QCD500 250 cms-medium analyzer QCD500 PERUGIA MC $folder
./runOnQueue.sh QCD1000 250 cms-medium analyzer QCD1000 PERUGIA MC $folder
#./runOnQueue.sh WJets 250 cms-medium analyzer WJets180 PERUGIA MC $folder
./runOnQueue.sh WJetsHT 250 cms-medium analyzer WJetsHT PERUGIA MC $folder
./runOnQueue.sh WJetsHT300 250 cms-medium analyzer WJetsHT300 PERUGIA MC $folder
./runOnQueue.sh SingleTop1 100 cms-medium analyzer SingleTop1 PERUGIA MC $folder
./runOnQueue.sh SingleTop2 100 cms-medium analyzer SingleTop2 PERUGIA MC $folder
./runOnQueue.sh SingleTop3 100 cms-medium analyzer SingleTop3 PERUGIA MC $folder
./runOnQueue.sh SingleTop4 100 cms-medium analyzer SingleTop4 PERUGIA MC $folder
./runOnQueue.sh SingleTop5 100 cms-medium analyzer SingleTop5 PERUGIA MC $folder
./runOnQueue.sh SingleTop6 100 cms-medium analyzer SingleTop6 PERUGIA MC $folder
qstat | grep spiezia | wc -l

### tauMC ###
#./runOnQueue.sh ZH1000 10 cms-short tauMC ZH1000 PERUGIA MC $folder
#./runOnQueue.sh ZH1500 10 cms-short tauMC ZH1500 PERUGIA MC $folder
#./runOnQueue.sh ZH2000 10 cms-short tauMC ZH2000 PERUGIA MC $folder
#./runOnQueue.sh ZH2500 10 cms-short tauMC ZH2500 PERUGIA MC $folder
##./runOnQueue.sh QCD1000 150 short tauMC QCD1000_tauMC PERUGIA MC $folder
#qstat | grep spiezia | wc -l

#### efficiency ###
#./runOnQueue.sh ZH1000    25  cms-short  efficiency ZH1000    PERUGIA MC $folder
#./runOnQueue.sh ZH1500    25  cms-short  efficiency ZH1500    PERUGIA MC $folder
#./runOnQueue.sh ZH2000    25  cms-short  efficiency ZH2000    PERUGIA MC $folder
#./runOnQueue.sh ZH2500    25  cms-short  efficiency ZH2500    PERUGIA MC $folder
#./runOnQueue.sh DY100     250 cms-medium efficiency DY100     PERUGIA MC $folder
#./runOnQueue.sh DY70      250 cms-medium efficiency DY70      PERUGIA MC $folder
#./runOnQueue.sh DYM50_100 250 cms-medium efficiency DYM50_100 PERUGIA MC $folder
#./runOnQueue.sh DYM50_70  250 cms-medium efficiency DYM50_70  PERUGIA MC $folder
##./runOnQueue.sh QCD250    250 cms-medium efficiency QCD250    PERUGIA MC $folder
##./runOnQueue.sh QCD500    250 cms-medium efficiency QCD500    PERUGIA MC $folder
##./runOnQueue.sh QCD1000   250 cms-medium efficiency QCD1000   PERUGIA MC $folder
#qstat | grep spiezia | wc -l

### analyzer - ZURICH ###
#./runOnQueue.sh RunA 50 short analyzer RunA ZURICH data $folder
#./runOnQueue.sh RunB 50 short analyzer RunB ZURICH data $folder
#./runOnQueue.sh RunC 50 short analyzer RunC ZURICH data $folder
#./runOnQueue.sh RunD 50 short analyzer RunD ZURICH data $folder
#./runOnQueue.sh ZH1000 25 short analyzer ZH1000 ZURICH MC $folder
#./runOnQueue.sh ZH1500 25 short analyzer ZH1500 ZURICH MC $folder
#./runOnQueue.sh ZH2000 25 short analyzer ZH2000 ZURICH MC $folder
#./runOnQueue.sh ZH2500 25 short analyzer ZH2500 ZURICH MC $folder
#./runOnQueue.sh DY100 100 short analyzer DY100 ZURICH MC $folder
#./runOnQueue.sh DY70 100 short analyzer DY70 ZURICH MC $folder
#./runOnQueue.sh DYM50_100 100 short analyzer DYM50_100 ZURICH MC $folder
#./runOnQueue.sh DYM50_70 100 short analyzer DYM50_70 ZURICH MC $folder
#./runOnQueue.sh WW 100 short analyzer WW ZURICH MC $folder
#./runOnQueue.sh WZ 100 short analyzer WZ ZURICH MC $folder
#./runOnQueue.sh ZZ 100 short analyzer ZZ ZURICH MC $folder
#./runOnQueue.sh TT 100 short analyzer TT ZURICH MC $folder
#./runOnQueue.sh QCD250 100 short analyzer QCD250 ZURICH MC $folder
#./runOnQueue.sh QCD500 100 short analyzer QCD500 ZURICH MC $folder
#./runOnQueue.sh QCD1000 100 short analyzer QCD1000 ZURICH MC $folder
#./runOnQueue.sh WJets 100 short analyzer WJets180 ZURICH MC $folder
#qstat | grep spiezia | wc -l


#### QCD ANALYZER #
#./runOnQueue.sh DY100 200 short QCD DY100_QCD ZURICH MC $folder
#./runOnQueue.sh DY70 200 short QCD DY70_QCD ZURICH MC $folder
#./runOnQueue.sh WW 200 short QCD WW_QCD ZURICH MC $folder
#./runOnQueue.sh WZ 200 short QCD WZ_QCD ZURICH MC $folder
#./runOnQueue.sh ZZ 200 short QCD ZZ_QCD ZURICH MC $folder
#./runOnQueue.sh TT 200 short QCD TT_QCD ZURICH MC $folder
#./runOnQueue.sh QCD250 200 short QCD QCD250_QCD ZURICH MC $folder
#./runOnQueue.sh QCD500 200 short QCD QCD500_QCD ZURICH MC $folder
#./runOnQueue.sh QCD1000 200 short QCD QCD1000_QCD ZURICH MC $folder
#./runOnQueue.sh WJets 200 short QCD WJets180_QCD ZURICH MC $folder
#./runOnQueue.sh ZH1000 25 short QCD ZH1000_QCD ZURICH MC $folder
#./runOnQueue.sh ZH1500 25 short QCD ZH1500_QCD ZURICH MC $folder
#./runOnQueue.sh ZH2000 25 short QCD ZH2000_QCD ZURICH MC $folder
#./runOnQueue.sh ZH2500 25 short QCD ZH2500_QCD ZURICH MC $folder
#./runOnQueue.sh RunA 100 short QCD RunA_QCD ZURICH data $folder
#./runOnQueue.sh RunB_final 100 short QCD RunB_final_QCD ZURICH data $folder
#./runOnQueue.sh RunC_final 100 short QCD RunC_final_QCD ZURICH data $folder
#./runOnQueue.sh RunD_final 100 short QCD RunD_final_QCD ZURICH data $folder
#./runOnQueue.sh RunB_topup 100 short QCD RunB_topup_QCD ZURICH data $folder
#./runOnQueue.sh RunC_topup 100 short QCD RunC_topup_QCD ZURICH data $folder
#./runOnQueue.sh RunD_topup 100 short QCD RunD_topup_QCD ZURICH data $folder
#qstat | grep spiezia | wc -l
#
#### fake rate ###
#./runOnQueue.sh RunA 50 short FakeRate RunA_FakeRate ZURICH data $folder
#./runOnQueue.sh RunB 50 short FakeRate RunB_FakeRate ZURICH data $folder
#./runOnQueue.sh RunC 50 short FakeRate RunC_FakeRate ZURICH data $folder
#./runOnQueue.sh RunD 50 short FakeRate RunD_FakeRate ZURICH data $folder
#
### JetIdStudy ###
#./runOnQueue.sh ZH1000 2 short JetIdStudy ZH1000_JetIdStudy ZURICH MC $folder
#./runOnQueue.sh ZH1500 2 short JetIdStudy ZH1500_JetIdStudy ZURICH MC $folder
#./runOnQueue.sh ZH2000 2 short JetIdStudy ZH2000_JetIdStudy ZURICH MC $folder
#./runOnQueue.sh ZH2500 2 short JetIdStudy ZH2500_JetIdStudy ZURICH MC $folder
#qstat | grep spiezia | wc -l